CrudProgrammers/CrudProgrammers/Models/Programmers.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudProgrammers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgrammersEntities1 : DbContext
    {
        public ProgrammersEntities1()
            : base("name=ProgrammersEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
    }
}

CrudProgrammers/CrudProgrammers/Models/Programmers.Designer.cs
// T4 code generation is enabled for model 'E:\Pessoal\bitbucket\Programmers\programmers\CrudProgrammers\CrudProgrammers\Models\Programmers.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

CrudProgrammers/CrudProgrammers/Models/Programmers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

CrudProgrammers/CrudProgrammers/Models/TB_USUARIO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudProgrammers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        public int ID { get; set; }
        public string NOME_COMPLETO { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
    }
}

CrudProgrammers/CrudProgrammers/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrudProgrammers.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CrudProgrammers/CrudProgrammers/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrudProgrammers.Models;

namespace CrudProgrammers.Controllers
{
    public class UsuarioController : Controller
    {
        private ProgrammersEntities1 db = new ProgrammersEntities1();

        // GET: Usuario
        public ActionResult Index(string NomeUsuario)
        {
            var usuario = new List<TB_USUARIO>();
            if (!string.IsNullOrEmpty(NomeUsuario))
            {
                usuario = db.TB_USUARIO.Where(x => x.NOME_COMPLETO.Contains(NomeUsuario)).ToList();
            }
            else
            {
                usuario = db.TB_USUARIO.ToList();
            }
            return View(usuario);
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_USUARIO tB_USUARIO = db.TB_USUARIO.Find(id);
            if (tB_USUARIO == null)
            {
                return HttpNotFound();
            }
            return View(tB_USUARIO);
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NOME_COMPLETO,EMAIL,TELEFONE")] TB_USUARIO tB_USUARIO)
        {
            if (ModelState.IsValid)
            {
                tB_USUARIO.TELEFONE = tB_USUARIO.TELEFONE.Replace("(", "").Replace(")", "").Replace("-", "").Replace(" ","").Trim();
                db.TB_USUARIO.Add(tB_USUARIO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tB_USUARIO);
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_USUARIO tB_USUARIO = db.TB_USUARIO.Find(id);
            if (tB_USUARIO == null)
            {
                return HttpNotFound();
            }
            return View(tB_USUARIO);
        }

        // POST: Usuario/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NOME_COMPLETO,EMAIL,TELEFONE")] TB_USUARIO tB_USUARIO)
        {
            if (ModelState.IsValid)
            {
                tB_USUARIO.TELEFONE = tB_USUARIO.TELEFONE.Replace("(", "").Replace(")", "").Replace("-", "").Replace(" ", "").Trim();
                db.Entry(tB_USUARIO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tB_USUARIO);
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_USUARIO tB_USUARIO = db.TB_USUARIO.Find(id);
            if (tB_USUARIO == null)
            {
                return HttpNotFound();
            }
            return View(tB_USUARIO);
        }

        // POST: Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TB_USUARIO tB_USUARIO = db.TB_USUARIO.Find(id);
            db.TB_USUARIO.Remove(tB_USUARIO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public string FormatTEL(string TEL)
        {
            string tel = string.Empty;
            if (TEL.Length <= 10)
                tel = Convert.ToUInt64(TEL).ToString("(##) ####-####");
            else if (TEL.Length > 10)
                tel = Convert.ToUInt64(TEL).ToString("(##) #####-####");

            return tel;
        }
    }
}

CrudProgrammers/CrudProgrammers/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CrudProgrammers/CrudProgrammers/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CrudProgrammers/CrudProgrammers/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CrudProgrammers/CrudProgrammers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand static-top">
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#" style="padding-right:35px">
        </button>
        <a class="navbar-brand mr-1" href="@Url.Action("Index", "Usuario")">@Html.Label("Crud Usuários")</a>
    </nav>
        <div class="container body-content" style="margin-top:10px;">
            @RenderBody()

        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

CrudProgrammers/CrudProgrammers/Views/Shared/_LayoutVazio.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <META HTTP-EQUIV="Content-Type"
          CONTENT="text/html; charset=ISO-8859-1">
    <title>Crud</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/Usuariocss")

</head>
<body>

    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Usuariojs")
    @RenderSection("scripts", required: false)
</body>
</html>

CrudProgrammers/CrudProgrammers/Views/Usuario/Create.cshtml
@model CrudProgrammers.Models.TB_USUARIO

@{
    Layout = Layout;
}


@section scripts{
    <script>

        $(function () {
            $("#TELEFONE").mask('(00) 0000-0000', { placeholder: "(__) ____-____" });
        
        });

    </script>
}

    <div class="card mb-3">
        <div class="card-header">
            <h5>Criar Usuário</h5>
        </div>
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("Nome Completo", htmlAttributes: new { @class = "control-label col-md-10" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NOME_COMPLETO, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NOME_COMPLETO, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("E-Mail", htmlAttributes: new { @class = "control-label col-md-10" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Telefone", htmlAttributes: new { @class = "control-label col-md-10" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TELEFONE, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TELEFONE, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Criar" class="btn btn-success" />

                            <a class="btn btn-secondary" href="@Url.Action("Index", "Usuario" )"> Voltar</a>
                        </div>
                    </div>
                </div>
            }

        </div>

    </div>

CrudProgrammers/CrudProgrammers/Views/Usuario/Delete.cshtml
@model CrudProgrammers.Models.TB_USUARIO

@{
    Layout = null;
}


<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Deseja excluir esse Usuário?</h4>
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayName("Usuário")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NOME_COMPLETO)
                </dd>
            </dl>
        </div>
        <div class="modal-footer">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Deletar" class="btn btn-success" />
                @Html.ActionLink("Fechar", "Index", null, new { @class = "btn btn-secondary" })
            </div>
            }

        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

CrudProgrammers/CrudProgrammers/Views/Usuario/Details.cshtml
@model CrudProgrammers.Models.TB_USUARIO

@{
    Layout = null;
}


<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Detalhes Usuário!</h4>
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        </div>
        <div class="modal-body">

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayName("Nome Completo")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NOME_COMPLETO)
                </dd>

                <dt>
                    @Html.DisplayName("Email")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EMAIL)
                </dd>

                <dt>
                    @Html.DisplayName("Telefone")
                </dt>

                <dd>
                    @if (@Html.DisplayFor(model => model.TELEFONE) != null)
                    {
                        string tel = Html.Action("FormatTEL", "Usuario", new { TEL = @Html.DisplayFor(model => model.TELEFONE) }).ToString();
                        @Html.Label("", String.Format("{0}", tel))
                    }
                </dd>

            </dl>
        </div>
        <div class="modal-footer">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                @Html.ActionLink("Editar", "Edit", new { id = Model.ID }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Fechar", "Index", null, new { @class = "btn btn-secondary" })
            </div>
            }

        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

CrudProgrammers/CrudProgrammers/Views/Usuario/Edit.cshtml
@model CrudProgrammers.Models.TB_USUARIO

@{
    Layout = Layout;
}



@section scripts{
    <script>
        $(function () {
            $("#TELEFONE").mask('(00) 0000-0000', { placeholder: "(__) ____-____" });

        });

    </script>
}

    <div class="card mb-3">
        <div class="card-header">
            <h5>Editar Usuário</h5>
        </div>
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ID)

                        <div class="form-group">
                            @Html.Label("Nome Completo", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NOME_COMPLETO, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NOME_COMPLETO, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("E-Mail", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Telefone", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.TELEFONE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TELEFONE, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Salvar" class="btn btn-success" />

                                <a class="btn btn-secondary" href="@Url.Action("Index", "Usuario" )"> Voltar</a>
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>

CrudProgrammers/CrudProgrammers/Views/Usuario/Index.cshtml
@model IEnumerable<CrudProgrammers.Models.TB_USUARIO>

@{
    Layout = Layout;
}

@section scripts{
    <script>
            var $ = jQuery.noConflict();
        $(function () {
            $(".btn-outline-info").click(function () {
                debugger;
                var id = $(this).attr("data-id");
                $("#modal").load("Usuario/Details?id=" + id, function () {
                    $("#modal").modal();
                })
            });

            $(".btn-outline-danger").click(function () {
                debugger;
                var id = $(this).attr("data-id");
                $("#modal").load("Usuario/Delete?id=" + id, function () {
                    $("#modal").modal();
                })
            });
        });

    </script>
}
    <div class="card mb-2">
        <div class="card-header">
            <h5>Filtros de Busca</h5>
        </div>
        <div class="card-body">

            @using (Html.BeginForm("Index",
                                     "Usuario",
                                     FormMethod.Post,
                                     new { enctype = "multipart/form-data" }))
            {

                <div class="form-horizontal">
                    <div class="row">

                        <div class="form-group">
                            @Html.Label("Nome Usuário", htmlAttributes: new { @class = "control-label col-md-10" })
                            <div class="col-12">
                                @Html.TextBox("NomeUsuario", ViewBag.NomeUsuario as string, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>

                <p>
                    <button class="btn btn-outline-primary"><i class="fas fa-fw fa-search fa-16"></i></button>
                </p>
            }
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-body">
            <p>

                <a class="btn btn-outline-success" href="@Url.Action("Create", "Usuario" )"><i class="fas fa-fw fa-plus fa-16"></i></a>

            </p>
                <div class="table-responsive fixed">
                    <table class="table table-bordered" id="dataTable" style="overflow-x: scroll;  table-layout: fixed;  width: 100%; " cellspacing="0">
                        <thead class="text-white thead-blue">
                            <tr>
                                <th></th>
                                <th style="width:300px !important">@Html.DisplayName("Nome Completo")</th>
                                <th style="width:300px !important">@Html.DisplayName("E-Mail")</th>
                                <th style="width:200px !important">@Html.DisplayName("Telefone")</th>
                            </tr>
                        </thead>

                        <tbody>

                            @foreach (var item in Model)
                            {

                            <tr>
                                <td>
                                    <button class="btn btn-outline-info" data-id="@item.ID"><i class="fas fa-fw fa-info fa-16"></i></button>
                                    <a class="btn btn-outline-warning" href="@Url.Action("Edit", "Usuario" , routeValues: new { Id = item.ID } )"><i class="fas fa-fw fa-edit fa-16"></i></a>
                                    <button class="btn btn-outline-danger" data-id="@item.ID"><i class="fas fa-fw fa-trash fa-16"></i></button>
                                    @*<a class="btn btn-outline-info" href="@Url.Action("Details", "Usuario", routeValues: new { Id = item.ID } )"><i class="fas fa-fw fa-info fa-16"></i></a>*@

                                    @*<a class="btn btn-outline-danger" href="@Url.Action("Delete", "Usuario" , routeValues: new { Id = item.ID } )"><i class="fas fa-fw fa-trash fa-16"></i></a>*@

                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NOME_COMPLETO)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EMAIL)
                                </td>
                                <td>
                                    @if (item.TELEFONE != null)
                                    {
                                        string tel = Html.Action("FormatTEL", "Usuario", new { TEL = item.TELEFONE }).ToString();
                                        @Html.Label("", String.Format("{0}", tel))
                                    }
                                </td>
                            </tr>

                            }
                        </tbody>
                    </table>
                </div>

        </div>
    </div>
    <div class="modal" id="modal">

    </div>